"use strict";
const Rules=window.MahjongRules;const TileAssets=window.TileAssets;const ResultShare=window.ResultShare;let gameState=null;let selectedTile=null;
const $=id=>document.querySelector(id);
const elements={startScreen:$("#start-screen"),playScreen:$("#play-screen"),resultScreen:$("#result-screen"),historySection:$("#history-section"),historyList:$("#tenpai-history-list"),startButton:$("#start-button"),restartButton:$("#restart-button"),againButton:$("#again-button"),saveResultButton:$("#save-result-button"),xPostButton:$("#x-post-button"),shareStatus:$("#share-status"),nextRoundButton:$("#next-round-button"),tilesLeft:$("#tiles-left"),discardCount:$("#discard-count"),tenpaiCount:$("#tenpai-count"),turnCount:$("#turn-count"),hand:$("#hand"),drawnTile:$("#drawn-tile"),discards:$("#discards"),message:$("#message"),kans:$("#kans"),kanArea:$("#kan-area"),handCountLabel:$("#hand-count-label"),kanButtons:$("#kan-buttons"),tenpaiPanel:$("#tenpai-panel"),waits:$("#waits"),resultTenpais:$("#result-tenpais"),resultTotalTenpais:$("#result-total-tenpais"),resultDiscards:$("#result-discards"),resultUsed:$("#result-used"),resultRemaining:$("#result-remaining")};
function tileName(tile){return tile.suit==="honor"?tile.value:`${tile.value}${{man:"萬",pin:"筒",sou:"索"}[tile.suit]}`;}
function styleTile(element,tile){element.className=`tile tile--${tile.suit}`;const image=document.createElement("img");image.src=TileAssets.imagePath(tile);image.alt="";image.draggable=false;element.replaceChildren(image);element.dataset.tileId=TileAssets.tileCode(tile);}
function tileButton(tile,onClick,extra="",selected=false){const b=document.createElement("button");b.type="button";styleTile(b,tile);if(extra)b.classList.add(extra);if(selected)b.classList.add("tile--selected");b.setAttribute("aria-label",`${tileName(tile)}${selected?"を捨てる":"を選択"}`);b.setAttribute("aria-pressed",String(selected));b.addEventListener("click",onClick);return b;}
function staticTile(tile){const s=document.createElement("span");styleTile(s,tile);s.setAttribute("aria-label",tileName(tile));return s;}
function renderUsedTiles(){const counts=Rules.usedTileCounts(gameState);const groups=[["萬子",0,9],["筒子",9,18],["索子",18,27],["字牌",27,34]];elements.discards.replaceChildren(...groups.map(([label,start,end])=>{const row=document.createElement("div");row.className="used-tile-group";row.setAttribute("aria-label",label);for(let order=start;order<end;order++){const item=document.createElement("div");item.className="used-tile-item";const tile=staticTile({...Rules.TILE_TYPES[order],order});const count=document.createElement("strong");count.textContent=`×${counts[order]}`;item.setAttribute("aria-label",`${tileName(Rules.TILE_TYPES[order])} 使用済み${counts[order]}枚`);item.append(tile,count);row.append(item);}return row;}));}
function renderHistory(){const history=gameState.tenpaiHistory||[];if(!history.length){const empty=document.createElement("p");empty.className="empty-state";empty.textContent="まだテンパイはありません";elements.historyList.replaceChildren(empty);return;}elements.historyList.replaceChildren(...history.map(entry=>{const item=document.createElement("article");item.className="tenpai-history__item";const title=document.createElement("strong");title.className="tenpai-history__number";title.textContent=`${entry.number}回目`;const hand=document.createElement("div");hand.className="history-hand";hand.setAttribute("aria-label",`${entry.number}回目のテンパイ形`);hand.append(...entry.hand.map(staticTile));const waits=document.createElement("div");waits.className="history-waits";const label=document.createElement("span");label.textContent="待ち";const tiles=document.createElement("div");tiles.className="history-wait-tiles";tiles.append(...entry.waits.map(order=>staticTile({...Rules.TILE_TYPES[order],order})));waits.append(label,tiles);item.append(title,hand,waits);return item;}));}
function chooseTile(area,index){const isSame=selectedTile?.area===area&&selectedTile.index===index;if(!isSame){selectedTile={area,index};render();return;}selectedTile=null;if(area==="hand")Rules.discardFromHand(gameState,index);else Rules.discardDrawn(gameState);render();}
function finishGame(){elements.playScreen.hidden=true;elements.resultScreen.hidden=false;elements.historySection.hidden=false;elements.restartButton.hidden=true;elements.resultTenpais.textContent=gameState.tenpais;elements.resultTotalTenpais.textContent=gameState.tenpais;elements.resultDiscards.textContent=gameState.discards.length;elements.resultUsed.textContent=Rules.usedTileCount(gameState);elements.resultRemaining.textContent=gameState.wall.length;renderHistory();}
function render(){if(gameState.finished){finishGame();return;}elements.tilesLeft.textContent=gameState.wall.length;elements.discardCount.textContent=Rules.usedTileCount(gameState);elements.tenpaiCount.textContent=gameState.tenpais;elements.turnCount.textContent=gameState.turn;elements.hand.replaceChildren(...gameState.hand.map((tile,index)=>tileButton(tile,()=>chooseTile("hand",index),"",selectedTile?.area==="hand"&&selectedTile.index===index)));elements.hand.style.gridTemplateColumns=`repeat(${gameState.hand.length},minmax(0,1fr))`;elements.handCountLabel.textContent=`左${gameState.hand.length}枚${gameState.drawnTile?"＋ツモ牌":""}`;elements.drawnTile.replaceChildren();if(gameState.drawnTile)elements.drawnTile.append(tileButton(gameState.drawnTile,()=>chooseTile("drawn",0),"tile--drawn",selectedTile?.area==="drawn"));
elements.kans.replaceChildren(...gameState.kans.map(kan=>{const g=document.createElement("div");g.className="kan-group";g.append(...kan.map(staticTile));return g;}));elements.kanArea.hidden=!gameState.kans.length;
const options=Rules.getKanOptions(gameState);elements.kanButtons.replaceChildren(...options.map(order=>{const tile=Rules.TILE_TYPES[order];const b=document.createElement("button");b.type="button";b.className="kan-button";b.textContent=`カン · ${tileName(tile)}`;b.addEventListener("click",()=>{selectedTile=null;Rules.declareKan(gameState,order);render();});return b;}));
elements.tenpaiPanel.hidden=!gameState.pendingTenpai;elements.waits.replaceChildren(...gameState.waits.map(order=>staticTile({...Rules.TILE_TYPES[order],order})));elements.message.textContent=gameState.pendingTenpai?"テンパイ成立！ 待ち牌を確認して次の局へ進んでください。":selectedTile?"選択した牌をもう一度タップすると捨てます":"捨てる牌を選んでください（2回タップ）";
renderUsedTiles();renderHistory();}
function startGame(){selectedTile=null;gameState=Rules.newGame();elements.shareStatus.textContent="";elements.startScreen.hidden=true;elements.resultScreen.hidden=true;elements.playScreen.hidden=false;elements.historySection.hidden=false;elements.restartButton.hidden=false;render();}
elements.startButton.addEventListener("click",startGame);elements.restartButton.addEventListener("click",startGame);elements.againButton.addEventListener("click",startGame);elements.nextRoundButton.addEventListener("click",()=>{selectedTile=null;Rules.advanceAfterTenpai(gameState);render();});
elements.saveResultButton.addEventListener("click",async()=>{elements.saveResultButton.disabled=true;elements.shareStatus.textContent="結果画像を作成しています…";try{const result=await ResultShare.saveResult(gameState,Rules,TileAssets);elements.shareStatus.textContent=result==="shared"?"共有メニューから画像の保存先を選んでください。":"PNG画像を保存しました。";}catch(error){elements.shareStatus.textContent=error?.name==="AbortError"?"画像の保存をキャンセルしました。":"画像を保存できませんでした。もう一度お試しください。";}finally{elements.saveResultButton.disabled=false;}});
elements.xPostButton.addEventListener("click",()=>ResultShare.openXPost(gameState.tenpais));
